server:
  port: 10000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.100:3306/gulimail_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t8zA16BS8ffPUTnwPrq
      secret-key: WYSktLTRg85V7SLdahaRneV7jbXGIM
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      #主键自增
      id-type: auto
      logic-delete-value: 1   #代表已删除
      logic-not-delete-value: 0   #代表未删除
logging:
  level:
    com.zzc.gulimail: debug